### ISSUE TITLE
url fragments break assets path

### ISSUE THREAD

**Issue by masiorama** [OscarBarrett/craft-twig-webpack-extension#3]
Hello there again, I'm having a problem here with my current configuration.
Probably it's on me, but so far I haven't found a solution.

The plugin works fine for homepage,  `/` and for entries like `/entry1`, `/entry2`, etc...
But for entries like `/subdir/entry` the path is wrong, since the assets is searched inside the `subdir` directory, even if my configuration is 
```
return [
    'outputDir' => 'assets'
];
```

The manifest is in the right place (`/assets`), and the entry for my assets inside the manifest are correct afaik: 
```
 "main.css": "/main.css",
 "main.js": "/main.js",
 "main.css.map": "/main.css.map",
 "main.js.map": "/main.js.map",
```
What am I doing wrong?
Thanks in advance!

**Comment by OscarBarrett** [comment]
Making `outputDir` absolute should fix it for you, e.g. `/assets`. The plugin doesn't add a leading slash, it will just take whatever you give it and pass that to the twig extension.

I could probably convert relative paths for `outputDir` to absolute by default... I can't really think of any use cases that might actually need relative paths.

**Comment by masiorama** [comment]
Actually I don't see any differences between `assets` and `/assets`.
The absolute for `outputDir` would definetely work for me, thanks! 👍 

update: actually now it works as you suggested... I guess I have some wrong webpack configuration or something like that...

**Comment by OscarBarrett** [comment]
To confirm, on a path like `/subdir/entry` it's trying to load the assets from `/subdir/<asset>`?

When using `outputDir` it gets passed as-is directly to the underlying twig extension, so if that didn't change anything for you it might be an issue with your configuration.

Could you provide your `output` settings from your webpack config?

Here's an example of how I currently have this set up on a project.

webpack config:
```
output: {
  path: path.resolve('web/resources'),
  publicPath: '/resources/',
  filename: '[name].js'
}
``` 

manifest content:
```
  "main.css": "main.css",
  "main.js": "main.js",
  "main.js.map": "main.js.map",
```

plugin `outputDir`: `/resources`

injected script in rendered template: `<script type="text/javascript" src="/resources/main.js"></script>`

**Comment by OscarBarrett** [comment]
I see my suggestion solved the issue for you :+1: I will close this off.
